name: Ruby Gem

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Setup credentials
      run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOM
          ---
          :github: Bearer ${GEM_HOST_API_KEY}
          EOM
          chmod 0600 ~/.gem/credentials
      ##############################
      # Build the gem from gemspec #
      ##############################
    - name: Build .gem
      run: gem build *.gemspec

      ###############################
      # Publish the gem to registry #
      ###############################
    - name: Publish .gem
      run: gem push --key github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
